name: fmt
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_screenutil: ^5.6.0
  connectivity_plus: 3.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 

  assets:
      # Add assets from the images directory to the application.
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Exo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/Exo2-Regular.ttf
          weight: 400
  uses-material-design: true
