# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference

version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test
      - run: flutter build apk --release
      - run:
          name: Bundle Install
          working_directory: android
          command: bundle install

      - run:
          name: Fastlane deploy to internal
          working_directory: android
          command: bundle exec 
     
