# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference

# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: cirrusci/flutter
#     steps:
#       - checkout
#       - run: flutter doctor
#       - run: flutter test
#       - run: flutter build apk --release
#       - run:
#           name: Bundle Install
#           working_directory: android
#           command: bundle install

#       - run:
#           name: Fastlane deploy to internal
#           working_directory: android
#           command: bundle exec 
     

alpha_stage:
     <<: *container_config
     steps:
       - checkout
       -
          run:
              command: bundle update fastlane && gem install bundler && bundle install
              name: configure build
       -
          restore_cache:
               <<: *general_cache_key
       -
          run:
               name: "Install Firebase CLI"
               command: |
                  curl -sL firebase.tools | bash
       -
          run:
               name: "Deploy alpha build to Firebase"
               command: |
                   bundle exec fastlane stage flavor:alpha branch:${CIRCLE_BRANCH} app_id:$app_id firebase_token:$Firebase_Cli_Token


workflows:
  version: 2
  build_tests_deploy:
    jobs:
       - build
       - test:
            requires:
               - build
       - alpha_stage:
            requires:
               - build
       - delta_stage:
            requires:
               - build
       - prod_stage:
            requires:
               - build
       - prod:
            filters:
             branches:
                only:
                   - master
                   - develop
            requires:
               - test
      - deploy:
            filters:
             branches:
                only:
                   - master
            requires:
               - prod

